### ISSUE TITLE
resource error

### ISSUE THREAD

**Issue by uname** [QuadFlask/colorpicker#17]
Error:(21, 21) No resource found that matches the given name: attr 'met_baseColor'.
Error:(22, 21) No resource found that matches the given name: attr 'met_floatingLabel'.
Error:(23, 21) No resource found that matches the given name: attr 'met_primaryColor'.

**Comment by swapps** [comment]
i have the same issue

**Comment by silicontao** [comment]
Cause is a missing dependency, see issue #24 for a workaround / fix.

**Comment by QuadFlask** [comment]
I remove hte MaterialEditText(met) dependency, so have a try
