### ISSUE TITLE
Library version seems to have a further dependency

### ISSUE THREAD

**Issue by silicontao** [QuadFlask/colorpicker#24]
Using the .aar prebuilt library, the following dependency was needed in the app build.gradle.

From https://github.com/rengwuxian/MaterialEditText

As external reference.....  compile 'com.rengwuxian.materialedittext:library:2.0.3'

As local .aar file..... compile (name:'MaterialEditText-2.1.3', ext:'aar')

**Comment by QuadFlask** [comment]
`exclude` would help this?

**Comment by silicontao** [comment]
Isn't exclude used for removing unecessary libraries from the build - http://stackoverflow.com/questions/20938158/gradle-for-android-aars-and-conditional-dependencies/20938258#20938258.

Since the MaterialEditText library is used for the editing option, isn't this more that an include is needed.

Maybe i'm missing something here.....

**Comment by QuadFlask** [comment]
I remove hte MaterialEditText(met) dependency, so have a try
