### ISSUE TITLE
Preference title cannot be set

### ISSUE THREAD

**Issue by JaySeeJC** [QuadFlask/colorpicker#27]
The title and summary for the ColorPickerPreference are unable to be set. Setting android:title does nothing. Please fix.
Screenshot from sample app:
![image](https://cloud.githubusercontent.com/assets/1485633/8143057/5358a3e2-1167-11e5-8c18-bb51f4497c82.png)

**Comment by QuadFlask** [comment]
I merged your pr to fix this. Thanks!
