### ISSUE TITLE
How to use ColorPickerView

### ISSUE THREAD

**Issue by uname** [QuadFlask/colorpicker#30]
Hi, I want to have the colorpicker in my layout as a view, NOT shown in a dialog as row.
I added your library and wrote these codes in my layout file:
    <com.flask.colorpicker.ColorPickerView
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"/>
But is not works, I got a null pointer error, so I add these code:
        if(renderer == null) {
            renderer = ColorWheelRendererBuilder.getRenderer(ColorPickerView.WHEEL_TYPE.FLOWER);
        }
in drawColorWheel function (ColorPickerView.java). But it still not works, program wont crash , however the view was not shown successfully!

**Comment by QuadFlask** [comment]
there is a [sample app](https://github.com/QuadFlask/colorpicker/tree/master/app). check out this.

the code what you want like below. 

``` xml
<?xml version="1.0" encoding="utf-8"?>
<LinearLayout
    xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:orientation="vertical">

    <com.flask.colorpicker.ColorPickerView
        android:id="@+id/color_picker_view"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        app:alphaSlider="true"
        app:density="12"
        app:lightnessSlider="true"
        app:wheelType="FLOWER"
        app:lightnessSliderView="@+id/v_lightness_slider"
        app:alphaSliderView="@+id/v_alpha_slider"
        />

    <com.flask.colorpicker.slider.LightnessSlider
        android:id="@+id/v_lightness_slider"
        android:layout_width="match_parent"
        android:layout_height="48dp"
        />

    <com.flask.colorpicker.slider.AlphaSlider
        android:id="@+id/v_alpha_slider"
        android:layout_width="match_parent"
        android:layout_height="48dp"
        />

</LinearLayout>
```
