### ISSUE TITLE
[current version]

### ISSUE THREAD

**Issue by swapps** [QuadFlask/colorpicker#35]
I didn't find out what to put for current version.

i have tried with : 

'com.github.QuadFlask:colorpicker:+'
'com.github.QuadFlask:colorpicker:0.0.9'
'com.github.QuadFlask:colorpicker:beta0.0.9'

without success, i'm getting failed to resolve

**Comment by QuadFlask** [comment]
Did you add 

```
    maven {
        url "https://jitpack.io"
    }
```

to `repositories` block in you `build.gradle` file?

**Comment by swapps** [comment]
Yes i did.

Cyril PREISS

www.swapps.fr http://www.swapps.fr/ 

Follow Swapps App dev on G+ https://plus.google.com/u/0/communities/108675494963196634299 

De : QuadFlask [mailto:notifications@github.com] 
Envoyé : lundi 10 août 2015 17:38
À : QuadFlask/colorpicker
Cc : swapps
Objet : Re: [colorpicker] [current version](#35)

Did you add 

```
maven {
    url "https://jitpack.io"
}
```

in you build.gradle file at the repositories block?

**Comment by QuadFlask** [comment]
Current version is `0.0.9`, so `com.github.QuadFlask:colorpicker:0.0.9` is the right.
