### ISSUE TITLE
ColorPickerView is not visiable on my Nexus6 device

### ISSUE THREAD

**Issue by uname** [QuadFlask/colorpicker#36]
RT
I use ColorPickerView in a layout. And it works on Nexus5, but not work on Nexus6, IT'S INVISIABLE:(

**Comment by uname** [comment]
Thanks @QuadFlask , but when will the bug be fixed?

**Comment by QuadFlask** [comment]
I think it's quite take time because I so busy right now. You could fix bug and send PR. I will check as soon as possible.

**Comment by QuadFlask** [comment]
I don't have Nexus6 but I fix #33 the suspect of this issue. Have a try

**Comment by uname** [comment]
Thanks @QuadFlask 
I have tried on my Nexus6, it's OK now!
