### ISSUE TITLE
Adding compile with latest version to gradle not working

### ISSUE THREAD

**Issue by adibuildup** [QuadFlask/colorpicker#44]
I tried to add a dependency to this project in my gradel like that:

 compile 'com.github.QuadFlask:colorpicker:0.0.9'
- I also tried lower case and different version but nothing seems to work.
-  only using the aar file works for me, But I saw you have newer versions that solved the problem of dependency in 'com.rengwuxian.materialedittext:library:2.1.4' but you don't have a new aar.

can please create newer aar file, or let me know how to add the latest version in gradle?

Thanks!

**Comment by QuadFlask** [comment]
did you add maven repo url?
open application module's `build.gradle` and add line below to `allprojects.repositories`

```
      maven { url "https://jitpack.io" }
```

for example `build.gradle` look like this

```
// Top-level build file where you can add configuration options common to all sub-projects/modules.

buildscript {
    repositories {
        jcenter()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:2.0.0-beta5'

        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

allprojects {
    repositories {
        jcenter()
        maven { url "https://jitpack.io" }
    }
}

task clean(type: Delete) {
    delete rootProject.buildDir
}
```

and add dependency like this (`0.0.1` has been released)

```
dependencies {
    compile 'com.github.QuadFlask:colorpicker:0.0.10'
}
```
