### ISSUE TITLE
Select multiple colors when pickerCount > 1

### ISSUE THREAD

**Issue by smedic** [QuadFlask/colorpicker#47]
When trying to set multiple colors by using ColorPickerDialogBuilder, for instance: text color and background color, I cannot acquire set colors.

```
.setPositiveButton("ok", new ColorPickerClickListener() {
                @Override
                public void onClick(DialogInterface dialog, int selectedColor, Integer[] allColors) {
                       //how to get chosen colors?
                }
})

```

I can get selectedColor, but how to know which index is that? Is that 1st color, 2nd etc.

**Comment by QuadFlask** [comment]
multiple color selecting is not implemented and I wrote issue #7.

**Comment by smedic** [comment]
When i set .showColorEdit(true) , then its ok. When I dont do this, all colors are never changed from inital values.

**Comment by smedic** [comment]
When i set .showColorEdit(true) , then its ok. When I dont do this, all colors are never changed from inital values.
