### ISSUE TITLE
Gradle Import Problem

### ISSUE THREAD

**Issue by moosabaloch** [QuadFlask/colorpicker#50]
Error:(28, 13) Failed to resolve: com.github.QuadFlask:colorpicker:0.0.10
same issue while importing from .aar
Android Studio 2.0
Gradle 2.1

**Comment by sdattatri** [comment]
I am getting this issue with version 0.0.13.  How did you fix this?

**Comment by mustafaozhan** [comment]
I have this issue also. I have a project which is using this library. Everything was fine before but right now I can not give update to my project bec of this library giving error with import (also with arr). Hope to solved soon i like the library and do not want to use alternatives.

Regards.
