### ISSUE TITLE
Align elements in dialog view

### ISSUE THREAD

**Issue by ghost** [QuadFlask/colorpicker#53]
According to Material Design guidelines all [dialog elements](https://www.google.com/design/spec/components/dialogs.html) should have equal padding of 24dp.  
![guidelines](https://material-design.storage.googleapis.com/publish/material_v_8/material_ext_publish/0Bzhp5Z4wHba3c3htV1IweVNKcFU/components_dialogs_updates1.png)  
Currently every element has its own padding. 
![now](https://cloud.githubusercontent.com/assets/543947/15814832/bc2d7b38-2bd1-11e6-8695-54e294b252dd.png)  
I think it should look somewhat like this  
![proposal](https://cloud.githubusercontent.com/assets/543947/15814830/bb1910fe-2bd1-11e6-8c47-d3c1026695ae.png)

**Comment by QuadFlask** [comment]
Fix paddings in dialog like below as you say. Thanks!
![hammerheadmob30yflask08202016175545](https://cloud.githubusercontent.com/assets/1639232/17830209/7db29c84-6700-11e6-8d37-f2d50091f3c8.png)
