### ISSUE TITLE
can not display color wheel in viewpager

### ISSUE THREAD

**Issue by hangox** [QuadFlask/colorpicker#63]
when I use it is fragment with viewpager. I found it can not display color wheel.Because It does not callback onWindowFocusChanged，so , can not create wheel bitmap.I fix it by this

```
@Override
    protected void onSizeChanged(int w, int h, int oldw, int oldh) {
        super.onSizeChanged(w, h, oldw, oldh);
        updateColorWheel();
    }
```

**Comment by QuadFlask** [comment]
Thank you! I will add your code.
