### ISSUE TITLE
Remove slidebar

### ISSUE THREAD

**Issue by OhhConti** [QuadFlask/colorpicker#72]
Hi, I want to know if there is the possibility to remove  the sliders, thanks.

**Comment by gitdefllo** [comment]
Did you try something like `mColorPickerView.setLightnessSlider(null);` and `mColorPickerView.setAlphaSlider(null);`? Not sure it's working, however, it's possible by XML. Simply add the widget without the sliders:

    <com.flask.colorpicker.ColorPickerView
        android:id="@+id/picker_background_color"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        app:lightnessSlider="false"
        app:alphaSlider="false"
        app:wheelType="FLOWER"
        app:density="12"/>

Nothing more. This will just display the wheel.
