### ISSUE TITLE
"Squash listener exceptions" - wtf?

### ISSUE THREAD

**Issue by ELO8C8** [QuadFlask/colorpicker#74]
In ColorPickerView's callOnColorChangedListeners method:

`				try {
					listener.onColorChanged(newColor);
				} catch (Exception e) {
					//Squash individual listener exceptions
				}
`

Why do you do this? This makes it a pain to use your library because you just hide the exceptions. If I have an exception I want my app to crash so I can find the cause. 
I have found other empty catches in this library but until it catches exceptions in the library only it doesn't bother me that much. But this one is 'funky'.

**Comment by QuadFlask** [comment]
thanks! I will fix this asap.
