### ISSUE TITLE
Disable alpha value

### ISSUE THREAD

**Issue by virajt71** [QuadFlask/colorpicker#79]
Hi, i have been trying to disable the alpha value & how to remove alpha value slider???

**Comment by LunaticMeta** [comment]
i want to know that too...

how about use colorPicker as a widget?
just create layout like this 


	<com.flask.colorpicker.ColorPickerView
		android:id="@+id/color_picker_view"
		android:layout_width="match_parent"
		android:layout_height="wrap_content"
		app:alphaSlider="true"
		app:density="12"
		app:lightnessSlider="true"
		app:wheelType="FLOWER"
		app:lightnessSliderView="@+id/v_lightness_slider"
	    app:alphaSliderView="@+id/v_alpha_slider"
		/>

	<com.flask.colorpicker.slider.LightnessSlider
		android:id="@+id/v_lightness_slider"
		android:layout_width="match_parent"
		android:layout_height="48dp"
		/>

**Comment by LunaticMeta** [comment]
use **showAlphaSlider(boolean)** function!!

        ColorPickerDialogBuilder
                        .with(context)
                        .setTitle("choose color")
                        .initialColor(mColor)
                        .wheelType(ColorPickerView.WHEEL_TYPE.FLOWER)
                        .density(12)
                        .showAlphaSlider(false)
                        .showLightnessSlider(true)
        ...
