### ISSUE TITLE
What is the ColorCode Type?

### ISSUE THREAD

**Issue by ghost** [QuadFlask/colorpicker#94]
What color code type of representation is this? How can I find the color I picked later elsewhere using the Integer value I picked?

**Comment by ghost** [comment]
@QuadFlask please respond to this issue.

**Comment by QuadFlask** [comment]
If I understood it well, the value is just integer(Red is 0xffff0000 == argb(255,255,0,0)).
You can set listener to picker view and listen value.

**Comment by ghost** [comment]
-196608 How do I find this color?

**Comment by QuadFlask** [comment]
That value is decimal number but you can conversion to hex like this.
```
"0x"+Integer.toHexString(selectedColor)
```
or, you can use bitwise operator.
```
blue = selectedColor & 0xff
green = selectedColor & 0xff00 >> 8
red = selectedColor & 0xff0000 >> 16
alpha = selctedColor & 0xff000000 >> 24
```
that integer value would be use anywhere in android.

**Comment by ghost** [comment]
Thanks a lot.
