### ISSUE TITLE
ColorPickerView.setColor does not change its AlphaSlider color

### ISSUE THREAD

**Issue by amir-hg** [QuadFlask/colorpicker#98]
hello anybody cares 
i think i found a issue or missed something
ColorPickerView.setColor does not change its AlphaSlider color :(
i set alphaslider with  xml and i try to set color in runtime but it does not change alphaSlider color but percent of alphaSlider is set correcty

Thanks in Advance and best wishes

**Comment by PaulBreugnot** [comment]
Did you try to call explicitly alphaSlider.setColor(color) ?

**Comment by ZooMMaX** [comment]
add alpha channel in initialColor ()

.initialColor(0xFF123456);
